// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/Frylock-dev/users/internal/api/user"
	user2 "github.com/Frylock-dev/users/internal/repository/postgres/user"
	user3 "github.com/Frylock-dev/users/internal/service/user"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitUserAPI(conn *pgxpool.Pool) *user.API {
	repositoryUser := user2.NewRepository(conn)
	serviceUser := user3.NewService(repositoryUser)
	api := user.NewAPI(serviceUser)
	return api
}
